### ISSUE TITLE
Maven build using scala-2.12_spark-3.4.1 Fails

### ISSUE THREAD

**Issue by msetodev** [mspnp/spark-monitoring#228]
Error:

spark-monitoring-main/src/spark-listeners/src/main/scala/org/apache/spark/listeners/UnifiedSparkListener.scala:69: value sparkEventToJson is not a member of object org.apache.spark.util.JsonProtocol

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.8.1:compile (default) on project spark-listeners: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.8.1:compile failed: Compilation failed: InterfaceCompileFailed -> [Help 1]
